fix: error

diff --git a/.github/workflows/delete-airflow.yaml b/.github/workflows/delete-airflow.yaml
--- a/.github/workflows/delete-airflow.yaml
+++ b/.github/workflows/delete-airflow.yaml
@@ -24,14 +24,12 @@ jobs:
           echo running on branch ${REF_NAME}
           echo "REF_NAME=${REF_NAME}" >> $GITHUB_ENV
 
-      - name: delete airflow
+      - name: uninstall airflow
         run: |
-          cd airflow/lecture_2
-
-          helm template airflow --set appName=${REF_NAME} | kubectl delete -f -
+          echo "Uninstalling airflow-${REF_NAME}"
+          helm uninstall airflow-${REF_NAME} || echo "Release not found, skipping"
 
       - name: delete pg db
         run: |
           cd airflow/lecture_2
-
           cat job/db-delete.yaml | sed -r "s:BRANCH:${REF_NAME}:g" | kubectl apply -f -
